### ISSUE TITLE
thunar-gpg-info.sh only shows sender not recipient

### ISSUE THREAD

**Issue by tristan-k** [cytopia/thunar-custom-actions#10]
`thunar-gpg-info.sh` only show the identity of the sender not of the recipient. 

How is to supposed to get the identity of the recipient if you query gpg with `gpg --list-secret-keys` shouldnt it be `gpg --list-public-keys,`. Otherwise gpg only prints your own identity (sender) not the recipient.

```
zenity --info --no-markup --text="Encrypted for: ${recipientKey} ${recipient}"
```

Or did you mean `Encrypted from:`?

**Comment by cytopia** [comment]
Hmm, I just double checked.
Here it shows for whom it is encrypted.

**Comment by tristan-k** [comment]
Which OS?

**Comment by cytopia** [comment]
I tested it yesterday on OSX:

``` shell
$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016

$ zenity --version
2016-05-19 10:00:27.994 zenity
```

**Comment by cytopia** [comment]
@tristan-k 
Should be fixed now
