### ISSUE TITLE
Thunar encrypt is not working

### ISSUE THREAD

**Issue by jccall80** [cytopia/thunar-custom-actions#13]
Hi 

In my case Thunar encrypt is not working because is not able to detect my public and private keys

I think the error is in the sed parameter of this fileds

`	pubkeys="$(gpg --list-public-keys \
	  | grep -A 1 "^pub" \
	  | sed -n -e "s:^pub *\([A-Za-z0-9]\+\)/\([A-F0-9]\+\) .*$:\1 \2:p" -e "s:^uid *\(.*\)$:\"\1\":p" \
	  | tr '\n' ' ')"`

`	seckeys="$(gpg --list-secret-keys \
	  | grep -A 1 "^sec" \
	  | sed -n -e "s:^sec *\([A-Za-z0-9]\+\)/\([A-F0-9]\+\) .*$:\1 \2:p" -e "s:^uid *\(.*\)$:\"\1\":p" \
	  | tr '\n' ' ')"`

**Comment by cytopia** [comment]
@jccall80 Please check again, I have completely rewritten and merged gpg-encrypt: #17 .
