### ISSUE TITLE
Algorithm field grayed out 

### ISSUE THREAD

**Issue by obaino** [cytopia/thunar-custom-actions#19]
I am using Debian 9 xfce.
on the dialogue box the algorithm field is grayed out.
I choose encrypt and I enter a key but I cannot pick an algorithm.

This returns:
enc: Unknown cipher  
enc: Use -help for summary.
return code: 1

![screenshot_2017-09-12_17-44-51](https://user-images.githubusercontent.com/6555722/30332080-27959aea-97e2-11e7-96de-0670718b1a72.png)
![screenshot_2017-09-12_17-45-09](https://user-images.githubusercontent.com/6555722/30332081-2799ac16-97e2-11e7-9edb-7a1a6bcc82d0.png)

**Comment by cytopia** [comment]
Looks like some options from openssl have changed again.

**Comment by cytopia** [comment]
Its fixed :-)
Sorry for the late reply
