### ISSUE TITLE
Debian 8 and thunar-gpg-encrypt.sh

### ISSUE THREAD

**Issue by pachanka** [cytopia/thunar-custom-actions#6]
Hi, I ran across your scripts and gave them a try in a (fresh) Debian stretch install and only had one problem with it.

For some reason the bits and key columns used in the `chooseRecipient` and `chooseSecret` were reversed (maybe gpg's version? mine is 1.4.20) and zenity was trying to use the bits instead of the key name for encryption resulting in an error. So after a `apt-get install pinentry-gtk2`:

`gpg: skipped "2048R": secret key not available`

Setting the collumn to `--print-column=2` and swapping places for
`--column=\"Bit\" --column=\"Key\" --column=\"Recipient\" ${pubkeys}"`
instead of
`--column=\"Key\" --column=\"Bit\" --column=\"Recipient\" ${pubkeys}"`

That fixed it for me.

**Comment by cytopia** [comment]
Hi @pachanka ,

thanks for reporting, I will look into this.

**Comment by tristan-k** [comment]
@pachanka This helped a lot. Thanks! 

@cytopia I can confirm the issue. Running on:

```
OS: Debian testing stretch
Kernel: x86_64 Linux 4.5.0-2-amd6
```

**Comment by cytopia** [comment]
Thanks everybody
