### ISSUE TITLE
Funtoo, upload to imgur not working

### ISSUE THREAD

**Issue by lozenge57** [cytopia/thunar-custom-actions#7]
```
 »»»» ./Scripts/thunar-upload-to-imgur.sh /home/lozenge/Wallpaper/paper1.png                                                                                                                                             0|05:06:30
Failed to execute process './Scripts/thunar-upload-to-imgur.sh'. Reason:
exec: Exec format error
The file './Scripts/thunar-upload-to-imgur.sh' is marked as an executable but could not be run by the operating system.

```

**Comment by lozenge57** [comment]
Realized I was running fish, but upon changing to bash:

```
lozenge@ramtag ~ $ ./Scripts/thunar-upload-to-imgur.sh /home/lozenge/Wallpaper/paper1.png 
./Scripts/thunar-upload-to-imgur.sh: line 5: syntax error near unexpected token `newline'
./Scripts/thunar-upload-to-imgur.sh: line 5: `<!DOCTYPE html>'
lozenge@ramtag ~ $ 
```

**Comment by cytopia** [comment]
Hi @lozenge57 

could you run it with `-x` please and paste the output

``` shell
 bash -x ./thunar-upload-to-imgur.sh -f /home/lozenge/Wallpaper/paper1.png 
```

**Comment by lozenge57** [comment]
```
[~]                                                                             
 »»»» cd /home/lozenge/Scripts/                                       0|04:02:30
[~/Scripts]                                                                     
 »»»» bash -x ./thunar-upload-to-imgur.sh -f /home/lozenge/Wallpaper/paper1.png 

./thunar-upload-to-imgur.sh: line 5: syntax error near unexpected token `newline'
./thunar-upload-to-imgur.sh: line 5: `<!DOCTYPE html>'
[~/Scripts]                                                                     
 »»»»                                                                 2|04:02:42


```

**Comment by cytopia** [comment]
Hmm this looks strange. Actually `bash -x` should show every single line processed by the script.

In my case it starts like this:

``` shell
 bash -x  thunar-upload-to-imgur.sh -f ~/Pictures/pic.jpg
+ getopts :f:cw:h:t: i
+ case "${i}" in
+ f=/home/cytopia/Pictures/pic.jpg
+ getopts :f:cw:h:t: i
+ shift 2
+ '[' -z /home/cytopia/Pictures/pic.jpg ']'
+ command -v zenity
+ command -v curl
+ command -v gawk
...
```

In your case it complains about line `5` , but this line does not contain any actual code, just comments.

And the following part of your first run is missing the `-f` option

> ``` shell
> lozenge@ramtag ~ $ ./Scripts/thunar-upload-to-imgur.sh /home/lozenge/Wallpaper/paper1.png 
> ./Scripts/thunar-upload-to-imgur.sh: line 5: syntax error near unexpected token `newline'
> ./Scripts/thunar-upload-to-imgur.sh: line 5: `<!DOCTYPE html>'
> lozenge@ramtag ~ $ 
> ```

This should actually even throw an error instead of doing any uploads. Something like this:

``` shell
./thunar-upload-to-imgur.sh ~/Pictures/pic.jpg
Error - no file specified
./thunar-upload-to-imgur.sh -f <filename> [-w width(int)] [-h height(int)] [-t window-title]
```

So just to be super sure, can you check if it is actually this script your are using: https://github.com/cytopia/thunar-custom-actions/blob/master/thunar-upload-to-imgur.sh

And what is your output from

``` shell
which bash
```

And 

``` shell
bash --version
```

Also did you create any aliases on `curl`, `zenity`, `grep`, etc? Can you run the following please:

``` shell
alias
```

**Comment by lozenge57** [comment]
Well I double checked the script...
And here are the commands:

```
[~]                                                                                                                
 »»»» bash                                                                                               0|00:09:26
lozenge@ramtag ~ $ alias
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias grep='grep --colour=auto'
alias ls='ls --color=auto'
lozenge@ramtag ~ $ which bash
/bin/bash
lozenge@ramtag ~ $ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
lozenge@ramtag ~ $ 

```

**Comment by cytopia** [comment]
I searched a bit about this error:

>  »»»» ./Scripts/thunar-upload-to-imgur.sh /home/lozenge/Wallpaper/paper1.png                                                                                                                                             0|05:06:30
> Failed to execute process './Scripts/thunar-upload-to-imgur.sh'. Reason:
> exec: Exec format error
> The file './Scripts/thunar-upload-to-imgur.sh' is marked as an executable but could not be run by the operating system.

I guess the `is marked as an executable but could not be run by the operating system.` indicates some local misconfiguration/error.
- https://sourceforge.net/p/fish/mailman/message/23375483/
- https://bbs.archlinux.org/viewtopic.php?id=131777
- https://github.com/fish-shell/fish-shell/issues/1281
- https://serverfault.com/questions/417365/bin-bash-exec-format-error

The only other idea I have left is to change the shebang in the first line of the script from

``` shell
#!/usr/bin/env bash
```

to

``` shell
#!/bin/bash
```

Also, what about the other scripts? Do they run fine or do they throw a similar error?

**Comment by cytopia** [comment]
I marked it as invalid, as it seems to be a local issue not related to the script.
If I am mistaken feel free to open this again.
