### ISSUE TITLE
upload-to-imgur.sh not displaying upload URL

### ISSUE THREAD

**Issue by shiburizu** [cytopia/thunar-custom-actions#8]
It's come to my attention that uploading an image through the imgur script displays a zenity window with no URL. Also spits out a 'no such option' for -f.

`kevin@volt-Thinkpad-T42 ~/Pictures $ thunar-upload-to-imgur.sh -f starwars.png`
`This option is not available. Please see --help for all possible usages.`
Linux Mint 17.3, screenie: http://i.imgur.com/mV0kmVv.png

**Comment by cytopia** [comment]
Could it be that the IMGUR_KEY (which is inside the script) has invalidated?

**Comment by cytopia** [comment]
They seem to have changed the API for uploading.

I just tried it via this url: `https://api.imgur.com/3/gallery.xml` but it requires authentication and my current Imgur key does not work.

**Comment by bazz1tv** [comment]
Would love to see progress on this. Thank you

**Comment by matiasw** [comment]
It seems like the access key needs to be replaced by an OAuth2 Client ID. 

> "Each client must register their application and receive the client_id and client_secret.
> For public read-only and anonymous resources, such as getting image info, looking up user comments, etc. all you need to do is send an authorization header with your client_id in your requests. This also works if you'd like to upload images anonymously"

so that should be enough for our purposes.
Is this application registered? If so, could the client ID be patched into the request?

**Comment by matiasw** [comment]
I have a Pull Request that fixes my problems with upload-to-imgur:  https://github.com/cytopia/thunar-custom-actions/pull/15
