### ISSUE TITLE
thunar-openssl-encrypt-decrypt.sh: Syntax error: "&" unexpected

### ISSUE THREAD

**Issue by tristan-k** [cytopia/thunar-custom-actions#9]
`thunar-openssl-encrypt-decrypt.sh` seems to be broken. There something wrong on [Line 82](https://github.com/cytopia/thunar-custom-actions/blob/master/thunar-openssl-encrypt-decrypt.sh#L82).

```
$ sh thunar-openssl-encrypt-decrypt.sh -f /path/to/some/file.ext
thunar-openssl-encrypt-decrypt.sh: 82: thunar-openssl-encrypt-decrypt.sh: Syntax error: "&" unexpected
```

**Comment by cytopia** [comment]
Fixed :-)
